# This file is a template, and might need editing before it works on your project.
---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry


variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - build
  - deploy
  - leaks

leaks:
  image:
    name: "zricethezav/gitleaks"
    entrypoint: [""]
  script:
    - gitleaks -v --path=./

test:
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo
  except:
    - master

build:
  image: registry.gitlab.com/pages/hugo:latest
  stage: build
  script:
    - hugo
  artifacts:
    paths:
      - public/
  only:
    - master

deploy:
  stage: deploy
  image: microsoft/azure-cli
  dependencies:
    - build
    - leaks
  script:
    - az storage blob upload-batch --destination '$web' --source public/ --account-name personalblog --account-key $AZURE_STORAGE_KEY
  only:
    - master
