# This file is a template, and might need editing before it works on your project.
---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry


variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo
  except:
    - master

build:
  stage: build
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo
  only:
    - master

deploy:
  stage: deploy
  image: microsoft/azure-cli
  dependencies:
    - build
  script:
    - az storage blob upload-batch --destination '$web' --source public/ --account-name personalblog --account-key $AZURE_STORAGE_KEY
  only:
    - master
