baseURL = "https://blog.coltonherrod.com"
languageCode = "en-us"
title = "Colton Herrod, DevOps Engineer"
theme = "m10c"

[params]
  author = "Colton Herrod"
  description = "Thoughts and experiences from a DevOps consultant."
  [[params.social]]
    name = "github"
    url = "https://github.com/gohugoio"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gohugoio"


[Menus]
  main = [
    {Name = "Github", URL = "https://github.com/username/"},
    {Name = "LinkedIn", URL = "https://www.linkedin.com/in/username/"}
  ]
