baseURL = "https://blog.coltonherrod.com"
languageCode = "en-us"
title = "Colton Herrod, DevOps Engineer"
theme = "m10c"

[params]
  author = "Colton Herrod"
  description = "Thoughts and experiences from a DevOps consultant."
  [[params.social]]
    name = "github"
    url = "https://github.com/ColtonHerrod"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/colton-herrod-76a68693/"


[Menus]
  main = [
    {Name = "Github", URL = "https://github.com/ColtonHerrod"},
    {Name = "LinkedIn", URL = "https://www.linkedin.com/in/colton-herrod-76a68693/"}
  ]
