name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Initialize submodules
      run: git submodule update --init --recursive 
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.0
    - name: Build the Hugo project
      run: hugo -D
