name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodule checkout
      run: git submodule update --init --recursive
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.0
    - name: Build the Hugo project
      run: hugo
    - name: Upload to blob storage
      run: az storage blob upload-batch --destination personal-blog --source public/ --account-name personalblog --account-key ${{secrets. AZURE_STORAGE_KEY}}
