name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.0
    - name: Build the Hugo project
      run: hugo -D
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      run: az storage blob upload-batch --destination personal-blog --source public/
